Kpi balance
omar-al-hendi/MyCovidView pull request #35
Opened 2023-06-08 15:38 UTC by Leon-Chin

this is the kpi and balanced board page

2023-06-08 16:09 UTC, Leon-Chin commented
already resolved the conflicts

2023-06-09 16:24 UTC, sulaimanmhashim approved these changes

2023-06-09 23:48 UTC, omar-al-hendi requested changes

2023-06-09 23:48 UTC, omar-al-hendi commented on src/pages/Balanceboard.tsx
> +        setRtkag(rtkag)
Hi Lei, you could put this in the loader function and return xArr, pcr, rtkag as an object like this `{ xArr, pcr, rtkag }`

2023-06-09 23:48 UTC, omar-al-hendi commented on src/pages/Balanceboard.tsx
> +    }, [])
if you use the loader we would not need to use these too

2023-06-09 23:48 UTC, omar-al-hendi commented on src/pages/KpiDashboard.tsx
> +    }, [])
Same here bro, I suggest putting it in a loader function so we get better performance

2023-06-09 23:48 UTC, omar-al-hendi commented on yarn.lock
> +
Aslo please delete the `yarn.lock` file we are using npm

2023-06-10 02:18 UTC, closed without merging

2023-06-10 02:19 UTC, HeLinChooi commented
Since a new PR [feat: add kpi and balanced board](https://github.com/omar-al-hendi/MyCovidView/pull/37) has been made so this PR I am closing this PR.