visualize line, area chart, and scatter plot
omar-al-hendi/MyCovidView pull request #36
Opened 2023-06-08 16:30 UTC by zhihui218

2023-06-08 16:38 UTC, omar-al-hendi commented
Hi, thansk for your contribution, I see that the data is static, the loaders data are not getting passed to the charts, would like to proceed with it ? @zhihui218 

And did you consider putting all your charts in the same page?

2023-06-09 08:04 UTC, sulaimanmhashim submitted a review, later dismissed

2023-06-10 02:13 UTC, HeLinChooi requested changes
Yup, I think putting all charts into a page is better so it is consistent for our project

2023-06-10 17:54 UTC, zhihui218 commented
alright, will amend soon.

2023-06-11 16:54 UTC, closed without merging